[package]
name = "minix"
license = "MIT"
version = "0.1.0"
edition = "2021"
author = [ "kremilly" ]
description = "A straightforward minifier for JavaScript and CSS files, developed using Rust. This tool efficiently reduces the size of JS and CSS files by removing unnecessary characters, whitespace, and comments without affecting functionality."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1.4"
mime = "0.3.13"
figlet-rs = "0.1.3"
colored = "2.0"
clap = { version = "4.4.8", features = ["cargo", "derive"] }