[package]
name = "minix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1.4"
mime = "0.3.13"
figlet-rs = "0.1.3"
colored = "2.0"
clap = { version = "4.4.8", features = ["cargo", "derive"] }